baseURL: https://beamish-crumble-091341.netlify.app/
languageCode: en-us
title: TPA Real Estate
theme: hugo-PaperMod

outputs:
    home:
        - HTML
        - RSS
        - JSON 

params:
   ShowShareButtons: true
   ShowPostNavLinks: true
   fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
        main:
                - identifier: posts
                  name: Posts
                  url: /posts/
                  weight: 10
                - identifier: archives
                  name: Archive
                  url: /archives/
                  weight: 20
                - identifier: search
                  name: Search
                  url: /search/
                  weight: 30
                - identifier: tags
                  name: Tags
                  url: /tags/
                  weight: 40